### PR TITLE
c2 w3 UGL and assignment revisions

### PR DESCRIPTION
**Pull request by e7dud7e**
* Autograph basics
- Added markdown

* Autograph lesson 2
- Changed title at top of notebook.
- Added markdown to accompany each cell of code.
- Show before & after code in separate cells.

* C2W3_Assignment
- Added markdown to explain which functions to use at each graded cell.
- Added a hint for if they get the grader error "TypeError: Cannot convert 1e-07 to EagerTensor of dtype int64"
- Removed the helper function set_image_size(224) which just returns its input parameter. Replaced with 224.
- Replaced image_size with image_height and image_width to make it more clear that they need to pass in height and width to the resize function and not just one image_size.
- No longer make them complete the tf.print function for the training set (just for the validation set).  I'm worried that that they might get confused when they see None("'Step", None).  They will still complete the tf.print for validation set.

Next steps:
- It would help if each graded function had a unit test or some kind of code that helps them check if they did it right.

### CODE REVIEW

**Comment by andres-zartab** [comment]
@e7dud7e for what graded function did you get the "Cannot convert 1e-07 to EagerTensor of dtype int64" error?

**Comment by cfav-dev** [comment]
added a minor revision on the dataset split. for the merge, i think Andres should make the final call because some involve graded functions.

**Comment by andres-zartab** [comment]
re-deployed grader. Now train_one_step runs much faster with much less memory usage. Thanks @cfav-dev ! Merging and closing now

**Comment by andres-zartab** [comment]
Or maybe holding off, so @cfav-dev can add the public unit tests in this branch.

**Comment by cfav-dev** [comment]
will merge now and i'll add the public unit tests there. thanks!

**Pull request merged**
